remote_theme: konstantin-morenko/just-the-docs-reborn

title: (Бес)Смертная 18+
description: Мистический роман

aux_links:
  "Купить книгу":
    - "https://konstantin-morenko.ru/immortal-book/"
  "Другие книги":
    - "https://konstantin-morenko.ru/#books"
  "Константин Моренко":
    - "https://konstantin-morenko.ru"

ycnumber: 69954367
mathjax: false
